In [1]:
import sys
sys.path.append('..')
from src.create_train_data import *
from src.train import *
from src.model import Ner

In [2]:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [133]:
os.getcwd()

'/Users/rishabh/Documents/Personal/Projects/resume_parsing/data'

In [134]:
os.path.join('/Users/rishabh/Documents/Personal/Projects/resume_parsing/data','../Resumes')

'/Users/rishabh/Documents/Personal/Projects/resume_parsing/data/../Resumes'

In [132]:
dir(os)

['CLD_CONTINUED',
 'CLD_DUMPED',
 'CLD_EXITED',
 'CLD_TRAPPED',
 'DirEntry',
 'EX_CANTCREAT',
 'EX_CONFIG',
 'EX_DATAERR',
 'EX_IOERR',
 'EX_NOHOST',
 'EX_NOINPUT',
 'EX_NOPERM',
 'EX_NOUSER',
 'EX_OK',
 'EX_OSERR',
 'EX_OSFILE',
 'EX_PROTOCOL',
 'EX_SOFTWARE',
 'EX_TEMPFAIL',
 'EX_UNAVAILABLE',
 'EX_USAGE',
 'F_LOCK',
 'F_OK',
 'F_TEST',
 'F_TLOCK',
 'F_ULOCK',
 'MutableMapping',
 'NGROUPS_MAX',
 'O_ACCMODE',
 'O_APPEND',
 'O_ASYNC',
 'O_CLOEXEC',
 'O_CREAT',
 'O_DIRECTORY',
 'O_DSYNC',
 'O_EXCL',
 'O_EXLOCK',
 'O_NDELAY',
 'O_NOCTTY',
 'O_NOFOLLOW',
 'O_NONBLOCK',
 'O_RDONLY',
 'O_RDWR',
 'O_SHLOCK',
 'O_SYNC',
 'O_TRUNC',
 'O_WRONLY',
 'POSIX_SPAWN_CLOSE',
 'POSIX_SPAWN_DUP2',
 'POSIX_SPAWN_OPEN',
 'PRIO_PGRP',
 'PRIO_PROCESS',
 'PRIO_USER',
 'P_ALL',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_PGID',
 'P_PID',
 'P_WAIT',
 'PathLike',
 'RTLD_GLOBAL',
 'RTLD_LAZY',
 'RTLD_LOCAL',
 'RTLD_NODELETE',
 'RTLD_NOLOAD',
 'RTLD_NOW',
 'R_OK',
 'SCHED_FIFO',
 'SCHED_OTHER',
 'SCHED_RR',
 'SEEK_CUR',
 'SEE

In [3]:
vocab = get_vocab()

In [4]:
len(vocab)

9273

In [5]:
word2id = word_id(vocab)
len(word2id)

9273

In [6]:
tag_map = get_tags()
len(tag_map)

9

In [7]:
tag2id = id_tag(tag_map)
len(tag2id)

9

In [8]:
model = Ner({'vocab_size': len(vocab), 'embedding_dim': 200,
                 'lstm_hidden_dim': 100, 'number_of_tags': len(tag_map)})

In [9]:
model.load_state_dict(torch.load('../model/resume_ner_model.pt'))

<All keys matched successfully>

In [10]:
text = read_file('../data/Resumes/Madhuri Pawar.docx')

In [11]:
text

"roma mehta\nmadhuri pawar\n484 754 6872\nmadurichand@gmail.com\nsummary:\n· over 7+ years of experience as senior business analyst working in diverse work environment within the healthcare industry. excellent communication, writing and presentation skills. \n· experience in business analysis, specializing in requirement management, uses cases and project coordination. skilled in eliciting user demands, managing user requirements and translating them to functional and design specs.\n· strong expertise as an analyst in health insurance, mortgage, health care & medical and financial domains. proficient in creating requirement traceability matrix, workflow diagrams and uml based documentation. knowledge of icd 9, icd 10, ncpdp and hipaa edi transactions (4010, 5010).\n· has (3+) years of experience in edi/hipaa and facets (benefits enrollment, claims processing etc.,)\n· experience working with stakeholders, business owners and senior management. hands on experience in analyzing the busin

In [12]:
test_sentences, test_data = create_data(text, vocab)

In [13]:
test_sentences

[['roma', 'mehta'],
 ['madhuri', 'pawar'],
 ['484', '754', '6872'],
 ['madurichand@gmail.com'],
 ['summary:'],
 ['·',
  'over',
  '7+',
  'years',
  'of',
  'experience',
  'as',
  'senior',
  'business',
  'analyst',
  'working',
  'in',
  'diverse',
  'work',
  'environment',
  'within',
  'the',
  'healthcare',
  'industry.',
  'excellent',
  'communication,',
  'writing',
  'and',
  'presentation',
  'skills.'],
 ['·',
  'experience',
  'in',
  'business',
  'analysis,',
  'specializing',
  'in',
  'requirement',
  'management,',
  'uses',
  'cases',
  'and',
  'project',
  'coordination.',
  'skilled',
  'in',
  'eliciting',
  'user',
  'demands,',
  'managing',
  'user',
  'requirements',
  'and',
  'translating',
  'them',
  'to',
  'functional',
  'and',
  'design',
  'specs.'],
 ['·',
  'strong',
  'expertise',
  'as',
  'an',
  'analyst',
  'in',
  'health',
  'insurance,',
  'mortgage,',
  'health',
  'care',
  '&',
  'medical',
  'and',
  'financial',
  'domains.',
  'profi

In [14]:
batch_size = 32

In [15]:
num_batches = math.ceil(len(test_data)/batch_size)
num_batches

5

In [16]:
len(test_data)

129

In [17]:
batch_sent = create_test_batch(test_data, 0, 32)

In [18]:
len(batch_sent)

32

In [19]:
batch_sent

tensor([[   0,    0,    1,  ...,    1,    1,    1],
        [5893,    0,    1,  ...,    1,    1,    1],
        [   0,    0,    0,  ...,    1,    1,    1],
        ...,
        [9025, 2012, 1916,  ...,    1,    1,    1],
        [9025, 2012, 4276,  ...,    1,    1,    1],
        [9025, 8396, 2012,  ...,    1,    1,    1]])

In [20]:
res = model(batch_sent)

In [21]:
res

tensor([[-5.6664, -5.3699, -0.0607,  ..., -5.5130, -5.5459, -5.7211],
        [-6.6405, -6.3168, -0.0203,  ..., -6.4947, -6.5702, -6.8349],
        [-6.9167, -6.5568, -0.0364,  ..., -6.7962, -6.8723, -7.0921],
        ...,
        [-6.6554, -6.6128, -0.3208,  ..., -6.9109, -6.8925, -6.9636],
        [-6.6554, -6.6128, -0.3208,  ..., -6.9109, -6.8926, -6.9636],
        [-6.6555, -6.6129, -0.3208,  ..., -6.9110, -6.8927, -6.9637]],
       grad_fn=<LogSoftmaxBackward>)

In [64]:
tag = np.argmax(res.detach().numpy(),axis=1)
tag

array([2, 2, 2, ..., 2, 2, 2])

In [65]:
shape = batch_sent.shape

In [67]:
tag = tag.reshape(shape[0],shape[1])

In [68]:
tag.shape

(32, 42)

In [63]:
batch_sent.shape

torch.Size([32, 42])

In [125]:
def get_tags(tag,batch_sent):
    _tags = list()
    batch_sent = batch_sent.detach().numpy()
    print(type(batch_sent))
    for row in range(len(batch_sent)):
        for col in range(len(batch_sent[row])):
            if tag[row][col] not in [0,1,2]:
                ix = batch_sent[row][col]
                print(ix)
                _tags.append(word2id[ix])
    return _tags

In [126]:
type(batch_sent)

torch.Tensor

In [127]:
type(batch_sent.detach().numpy())

numpy.ndarray

In [128]:
4 not in [4,1,5]

False

In [129]:
tag[0][0]

2

In [130]:
get_tags(tag,batch_sent)

<class 'numpy.ndarray'>
5428
2266
7734
500
4064
5428
5428
500
500
500
500
500
500
500
7495
3799
2473
500
500
5434


['project',
 'management.',
 'ui',
 'ms',
 'statistical',
 'project',
 'project',
 'ms',
 'ms',
 'ms',
 'ms',
 'ms',
 'ms',
 'ms',
 'testing',
 'gap',
 'analysis.',
 'ms',
 'ms',
 'codes']